spring.application.name=FastXBackend
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/fastx
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=email_address
spring.mail.password=app_password
spring.mail.properties.mail.smtp.auth=true
management.endpoint.health.show-details=always
spring.mail.properties.mail.smtp.starttls.enable=true